### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by itutopia** [SmartIDE/SmartIDE#15]
boathouse-calculator git:(master) # 在 MacOS 上打开 终端应用(Terminal) 并复制粘贴本段脚本
git clone https://gitee.com/idcf-boat-house/boathouse-calculator.git
cd boathouse-calculator
smartide start

Cloning into 'boathouse-calculator'...
remote: Enumerating objects: 907, done.
remote: Counting objects: 100% (907/907), done.
remote: Compressing objects: 100% (412/412), done.
remote: Total 907 (delta 477), reused 877 (delta 457), pack-reused 0
Receiving objects: 100% (907/907), 4.34 MiB | 4.46 MiB/s, done.
Resolving deltas: 100% (477/477), done.
v0.1.7.1429
2021-12-02 10:26:19.986 INFO  SmartIDE启动中 ...
2021-12-02 10:26:19.986 INFO  读取工作区信息 ...
2021-12-02 10:27:32.127 INFO  工作区配置改变！
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1446cf4]

goroutine 1 [running]:
golang.org/x/crypto/ssh.(*Client).NewSession(0xc000550b00)
	/home/localadmin/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210921155107-089bfa567519/ssh/client.go:130 +0x14
github.com/leansoftX/smartide-cli/lib/common.(*SSHRemote).ExecSSHCommandRealTimeFunc(0xc0005407a0, {0xc000036b40, 0x1e}, 0x0)
	/home/localadmin/agents/agent01/_work/1/s/lib/common/sshremote.go:370 +0x85
github.com/leansoftX/smartide-cli/lib/common.(*SSHRemote).ExecSSHCommandRealTime(...)
	/home/localadmin/agents/agent01/_work/1/s/lib/common/sshremote.go:364
github.com/leansoftX/smartide-cli/cmd/dal.SSHVolumesConfig({_, _}, _, {{0x0, 0x0}, {0x0, 0x0, 0x0}, {{0x0, 0x0}, ...}, ...}, ...)
	/home/localadmin/agents/agent01/_work/1/s/cmd/dal/gitconfig.go:77 +0xbb
github.com/leansoftX/smartide-cli/cmd/dal.(*YamlFileConfig).ConvertToDockerCompose(0xc00054c0e0, {{0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/home/localadmin/agents/agent01/_work/1/s/cmd/dal/config.go:666 +0xe31
github.com/leansoftX/smartide-cli/cmd/start.ExecuteStartCmd({0x0, {0x0, 0x0}, {0xc00003c004, 0x5a}, {0x1961fa7, 0xe}, {0x0, 0x0}, {0x195be11, ...}, ...}, ...)
	/home/localadmin/agents/agent01/_work/1/s/cmd/start/local.go:54 +0x32a
github.com/leansoftX/smartide-cli/cmd.glob..func9(0x20a1e20, {0x20de6d0, 0x0, 0x0})
	/home/localadmin/agents/agent01/_work/1/s/cmd/start.go:56 +0x2b3
github.com/spf13/cobra.(*Command).execute(0x20a1e20, {0x20de6d0, 0x0, 0x0})
	/home/localadmin/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x20a07a0)
	/home/localadmin/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/localadmin/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/leansoftX/smartide-cli/cmd.Execute({{0xc000038430, 0xb}, {0xc000038400, 0xa}, {0xc000450bd0, 0x21}, {0xc000450d50, 0x28}, {0xc000450d70, 0x8}, ...})
	/home/localadmin/agents/agent01/_work/1/s/cmd/root.go:68 +0x79
main.main()
	/home/localadmin/agents/agent01/_work/1/s/main.go:35 +0xbb

**Comment by ups216** [comment]
@itutopia 此问题已经修复，请按照安装手册更新 **稳定版** 通道，当前版本为 v0.1.7.1456

https://smartide.dev/zh/docs/install/#%E7%A8%B3%E5%AE%9A%E7%89%88%E9%80%9A%E9%81%93

谢谢
