### ISSUE TITLE
希望官方能对若依项目进行模板适配

### ISSUE THREAD

**Issue by zzc7211** [SmartIDE/SmartIDE#23]
希望官方能对若依项目进行开发模板适配
https://gitee.com/y_project/RuoYi-Vue

**Comment by ups216** [comment]
我看行！

**Comment by chileeb** [comment]
> 希望官方能对若依项目进行开发模板适配 https://gitee.com/y_project/RuoYi-Vue

您好，请问你是这个项目的维护者吗？可以发邮件给我以为你提供支持。jilibin@leansoftx.com

**Comment by zzc7211** [comment]
我看官方已经对gin-vue-admin 项目进行了适配，所以就来提个建议，并非若依项目开发人员
目前后端使用spring boot框架的项目很多，其中若依项目比较流行，衍生项目也比较多。
希望官方能寻找适配一个后端使用spring boot框架的项目作为模板

**Comment by chileeb** [comment]
> 我看官方已经对gin-vue-admin 项目进行了适配，所以就来提个建议，并非若依项目开发人员 目前后端使用spring boot框架的项目很多，其中若依项目比较流行，衍生项目也比较多。 希望官方能寻找适配一个后端使用spring boot框架的项目作为模板

您好，感谢您的建议。我们会对若依项目进行关注。
关注您提到的“后端使用spring boot框架的项目作为模板”，这个您可以参考：https://github.com/idcf-boat-house
这个一个开源共创项目，包含Vue的前端以及SpringBoot的后端，使用swagger提供api，并使用了redis+mysql数据库。
SpringBoot后端地址：https://github.com/idcf-boat-house/boat-house-backend，在.ide文件夹中可以看到smartide的配置。
演示视频见：https://www.bilibili.com/video/BV1zb4y1i7B1

SmartIDE 操练起来！

**Comment by chileeb** [comment]
> 希望官方能对若依项目进行开发模板适配 https://gitee.com/y_project/RuoYi-Vue

请问是否已加入SmartIDE早鸟群，欢迎加入SmartIDE早鸟计划！
![image](https://smartide.cn/images/smartide-s-qrcode.png)
扫码添加 “小S“ 微信，加入SmartIDE社区早鸟计划！

https://smartide.cn/

**Comment by zzc7211** [comment]
感谢 我这就加一下

**Comment by ups216** [comment]
@zzc7211 感谢你的建议，我们会尽快完成适配。

**Comment by sunnywa** [comment]
这个是没有源码吗？ @ups216

**Comment by ups216** [comment]
@zzc7211 若依系统已经适配成功，做一些微调以后就会放出来。

<img width="2511" alt="2022-02-15_17-37-57" src="https://user-images.githubusercontent.com/1203500/154034872-ce7bfa79-e28b-4339-a4f1-7849a39876c3.png">

**Comment by zzc7211** [comment]
感谢，我看到ruoyi-vue仓库了，这就去体验一下

**Comment by ups216** [comment]
@zzc7211 若依项目已经适配完毕，请参考以下操作手册使用 
https://gitee.com/smartide/RuoYi-Vue/tree/smartide/.ide

另外，我们还会提供一段操作视频来演示这个操作过程

**Comment by ups216** [comment]
已经给若依发送了PR https://gitee.com/y_project/RuoYi-Vue/pulls/432
同时发布了B站视频 https://www.bilibili.com/video/BV13L4y1g75S/

这个issue现在关闭。
