### ISSUE TITLE
arm支持

### ISSUE THREAD

**Issue by wshshra** [SmartIDE/SmartIDE#29]
希望支持arm架构

我用的是 SmartIDE/server/deployment/docker-compose.yaml部署的
报错信息是
standard_init_linux.go:228: exec user process caused: exec format error

**Comment by zhouwenyang** [comment]
@wshshra 感谢反馈，后面我们所有的镜像会默认支持linux/amd64, linux/arm64

**Comment by ups216** [comment]
@wshshra arm支持已经完成，server安装脚本，镜像和node环境的开发者镜像已经发布。相关代码已经推送到这里
https://github.com/SmartIDE/SmartIDE/commit/5b3fe0e891f3f3d0a6d369e72bea0fb034bccccc

@zhouwenyang 把相关的交付内容在这里列一下。

**Comment by zhouwenyang** [comment]
### 已更新安装脚本（支持ARM64，AMD64）：https://github.com/SmartIDE/SmartIDE/blob/main/server/deployment/deployment_cn.sh

### 相关变更：
[https://github.com/SmartIDE/SmartIDE/commit/5b3fe0e891f3f3d0a6d369e72bea0fb034bccccc](url)


> 已更新SmartIDE 服务镜像以及相关Dockerfile（支持ARM64，AMD64）：

- [x] SmartIDE Web
- [x] SmartIDE API
- [x] SmartIDE CLI

> 已更新SmartIDE Server依赖基础镜像清单（支持ARM64，AMD64）：

- [x] registry.cn-hangzhou.aliyuncs.com/smartide/mysql:8.0.29
- [x] registry.cn-hangzhou.aliyuncs.com/smartide/redis:6.0.16
- [x] registry.cn-hangzhou.aliyuncs.com/smartide/phpmyadmin:5.1.1-fpm 
- [x] registry.cn-hangzhou.aliyuncs.com/smartide/portainer:1.24.2

> 已更新tekton相关组件镜像。
> 已更新安装脚本所有依赖工具（支持ARM64，AMD64）：Kubectl，Minikube，Docker-Compose
