### ISSUE TITLE
如何搭建本地插件市场

### ISSUE THREAD

**Issue by ccsyt1205** [SmartIDE/SmartIDE#31]
您好，我想搭建一个内网的本地的插件市场，就部署到单Linux服务器里，看smartIDE官网给的方法是azure服务器+blob storage云存储的方式，有没有部署到单Linux服务器的方法？谢谢啦

**Comment by zlweicoder** [comment]
<img width="675" alt="image" src="https://user-images.githubusercontent.com/13825714/179126135-9efa6ebd-c6c1-436d-8838-6102e5e7113a.png">
已在群中解答此问题，关闭此Issue。
还有其他问题请直接联系我或在此issue下方留言。
