### ISSUE TITLE
删除xtp.xtp-docker 和linxiao.xtp-docker两个测试包

### ISSUE THREAD

**Issue by linxiaolx-lx** [SmartIDE/SmartIDE#34]
删除xtp.xtp-docker 和linxiao.xtp-docker两个测试包
https://marketplace.smartide.cn/extension/xtp/xtp-docker
https://marketplace.smartide.cn/extension/linxiao/xtp-docker

**Comment by zlweicoder** [comment]
@linxiaolx-lx done
