### ISSUE TITLE
web端是否支持

### ISSUE THREAD

**Issue by EverCurse** [SmartIDE/SmartIDE#35]
之前有提到web端会上线 但是文档没看到有这部分介绍 请问目前是否支持web端

**Comment by ups216** [comment]
我猜测你说的web端是指在网页上直接创建和管理工作区，这个上线已经很久了，是 SmartIDE Server 的功能。你可以加入我们的早鸟群（在官网底部扫描二维码）就可以获取我们的 SaaS版本的账号，或者根据以下文档自行部署。

Server部署手册：https://smartide.cn/zh/docs/install/server/
Server快速开始：https://smartide.cn/zh/docs/quickstart/server/

当前我们支持使用linux主机或者k8s集群两类资源，如果要使用完整的web端操作需要使用k8s集群。
对使用linux主机的web完整操作正在开发中，很快也会上线。
